In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import pymongo
import datetime
from flask import Flask
from sqlalchemy import create_engine
import json

In [3]:
tiktok_csv = "Resources/tiktok.csv"
tiktok_df = pd.read_csv(tiktok_csv)
tiktok_df = tiktok_df.drop('duration_mins', 1)
tiktok_df = tiktok_df.drop('track_id', 1)
tiktok_df = tiktok_df.drop('artist_id', 1)
tiktok_df = tiktok_df.drop('key', 1)
tiktok_df = tiktok_df.drop('speechiness', 1)
tiktok_df = tiktok_df.drop('acousticness', 1)
tiktok_df = tiktok_df.drop('instrumentalness', 1)
tiktok_df = tiktok_df.drop('genre', 1)
tiktok_df = tiktok_df.drop('playlist_id', 1)
tiktok_df = tiktok_df.drop('playlist_name', 1)
tiktok_df = tiktok_df.drop('album_id', 1)
tiktok_df.head()

,track_name,artist_name,duration,release_date,popularity,danceability,energy,loudness,mode,liveness,valence,tempo
0,Lay It Down Gmix - Main,Lloyd,302186,2011-01-01,28,0.597,0.800,-5.423,0,0.1800,0.565,155.932
1,Bartender (feat. Akon),T-Pain,238800,2007-06-05,75,0.832,0.391,-8.504,1,0.2240,0.436,104.961
2,Bartender (feat. Akon),T-Pain,238800,2007-06-05,75,0.832,0.391,-8.504,1,0.2240,0.436,104.961
3,Chosen (feat. Ty Dolla $ign),Blxst,161684,2020-12-04,76,0.571,0.767,-5.160,1,0.0809,0.605,93.421
4,Tie Me Down (with Elley Duhé),Gryffin,218295,2018-08-03,72,0.548,0.839,-2.371,1,0.1020,0.314,98.932

In [4]:
apple_music = "Resources/audd_music_apple_music.csv"
apple_music_df = pd.read_csv(apple_music)
apple_music_df = apple_music_df.drop('url', 1)
apple_music_df = apple_music_df.drop('discNumber', 1)
apple_music_df = apple_music_df.drop('durationInMillis', 1)
apple_music_df = apple_music_df.drop('trackNumber', 1)
apple_music_df = apple_music_df.drop('composerName', 1)
apple_music_df = apple_music_df.drop('artwork.width', 1)
apple_music_df = apple_music_df.drop('artwork.height', 1)
apple_music_df = apple_music_df.drop('artwork.url', 1)
apple_music_df = apple_music_df.drop('artwork.bgColor', 1)
apple_music_df = apple_music_df.drop('artwork.textColor1', 1)
apple_music_df = apple_music_df.drop('artwork.textColor3', 1)
apple_music_df = apple_music_df.drop('artwork.textColor4', 1)
apple_music_df = apple_music_df.drop('artwork.textColor2', 1)
apple_music_df = apple_music_df.drop('albumName', 1)
apple_music_df = apple_music_df.drop('playParams.id', 1)
apple_music_df = apple_music_df.drop('playParams.kind', 1)
apple_music_df.head()

,isrc,artistName,genreNames,releaseDate,name
0,USUM72002041,Pop Smoke,"['Hip-Hop/Rap', 'Music']",2020-02-07,Element
1,DKBKA0201518,Sigurd Barrett,"[""Children's Music"", 'Music']",1999-01-01,Pilfingerdansen (Remix)
2,USRC11300246,Justin Timberlake,"['Pop', 'Music']",2013-02-11,Mirrors (Radio Edit)
3,GBKQU1777771,Pascal Letoublon,"['House', 'Music', 'Dance']",2017-09-05,Friendships
4,GBUM72002531,Sam Smith,"['Pop', 'Music']",2020-09-19,Diamonds

In [5]:
spotify_artist = "Resources/audd_music_spotify_music_artists.csv"
spotify_artist_df = pd.read_csv(spotify_artist)

spotify_artist_df.head()

,id,name,uri,href,external_urls
0,0eDvMgVFoNV3TpwtrVCoTj,Pop Smoke,spotify:artist:0eDvMgVFoNV3TpwtrVCoTj,https://api.spotify.com/v1/artists/0eDvMgVFoNV...,https://open.spotify.com/artist/0eDvMgVFoNV3Tp...
1,6EN9iGovybDcQZ2NtsqMFd,Sigurd Barrett,spotify:artist:6EN9iGovybDcQZ2NtsqMFd,https://api.spotify.com/v1/artists/6EN9iGovybD...,https://open.spotify.com/artist/6EN9iGovybDcQZ...
2,31TPClRtHm23RisEBtV3X7,Justin Timberlake,spotify:artist:31TPClRtHm23RisEBtV3X7,https://api.spotify.com/v1/artists/31TPClRtHm2...,https://open.spotify.com/artist/31TPClRtHm23Ri...
3,0oXTS2yHUnuji1R7kc9J9a,Pascal Letoublon,spotify:artist:0oXTS2yHUnuji1R7kc9J9a,https://api.spotify.com/v1/artists/0oXTS2yHUnu...,https://open.spotify.com/artist/0oXTS2yHUnuji1...
4,2wY79sveU1sp5g7SokKOiI,Sam Smith,spotify:artist:2wY79sveU1sp5g7SokKOiI,https://api.spotify.com/v1/artists/2wY79sveU1s...,https://open.spotify.com/artist/2wY79sveU1sp5g...

In [6]:
spotify_music = "Resources/audd_music_spotify_music.csv"
spotify_music_df = pd.read_csv(spotify_music)
spotify_music_df = spotify_music_df.drop('is_playable', 1)
spotify_music_df = spotify_music_df.drop('linked_from', 1)
spotify_music_df = spotify_music_df.drop('available_markets', 1)
spotify_music_df = spotify_music_df.drop('disc_number', 1)
spotify_music_df = spotify_music_df.drop('duration_ms', 1)
spotify_music_df = spotify_music_df.drop('href', 1)
spotify_music_df = spotify_music_df.drop('preview_url', 1)
spotify_music_df = spotify_music_df.drop('track_number', 1)
spotify_music_df = spotify_music_df.drop('uri', 1)
spotify_music_df = spotify_music_df.drop('album.name', 1)
spotify_music_df = spotify_music_df.drop('name', 1)
spotify_music_df = spotify_music_df.drop('album.album_group', 1)
spotify_music_df = spotify_music_df.drop('album.album_type', 1)
spotify_music_df = spotify_music_df.drop('album.id', 1)
spotify_music_df = spotify_music_df.drop('album.uri', 1)
spotify_music_df = spotify_music_df.drop('album.available_markets', 1)
spotify_music_df = spotify_music_df.drop('album.href', 1)
spotify_music_df = spotify_music_df.drop('album.images', 1)
spotify_music_df = spotify_music_df.drop('album.external_urls.spotify', 1)
spotify_music_df = spotify_music_df.drop('album.release_date', 1)
spotify_music_df = spotify_music_df.drop('album.release_date_precision', 1)
spotify_music_df = spotify_music_df.drop('external_ids.isrc', 1)
spotify_music_df = spotify_music_df.drop('external_urls.spotify', 1)
spotify_music_df = spotify_music_df.drop('artists_ids', 1)
spotify_music_df.head()

                       id  popularity explicit
0  57BGVV6wcyhbn3hsjlqEZB        82.0     True
1  1nM60x7ZOBAVVe3ipKxD8b        52.0    False
2  6ToFxXRBtl5TJFEyIoYK3f        65.0    False
3  3S2XkZJH5P3AqYk8ChYsWB        74.0    False
4  5hvwx5i67IwnCkjl9VHkNv        81.0    False

In [7]:
music = "Resources/audd_music.csv"
music_df = pd.read_csv(music)
music_df = music_df.drop('id', 1)
music_df = music_df.drop('song_link', 1)
music_df = music_df.drop('label', 1)
music_df.head()

,artist,title,album,release_date,timecode,apple_music.isrc,spotify.id
0,Pop Smoke,Element,Meet The Woo 2,2020-02-07,00:23,USUM72002041,57BGVV6wcyhbn3hsjlqEZB
1,Sigurd Barrett,Pilfingerdansen,Børnesange Fra Sigurds Bjørnetime – Børnemusik...,2020-07-03,00:33,DKBKA0201518,1nM60x7ZOBAVVe3ipKxD8b
2,Justin Timberlake,Mirrors,Mirrors,2013-03-13,03:37,USRC11300246,6ToFxXRBtl5TJFEyIoYK3f
3,Pascal Letoublon,Friendships,Friendships,2017-09-05,00:44,GBKQU1777771,3S2XkZJH5P3AqYk8ChYsWB
4,Sam Smith,Diamonds,Love Goes,2020-09-17,00:51,GBUM72002531,5hvwx5i67IwnCkjl9VHkNv

In [14]:
billboard_charts = "Resources/charts.csv"
billboard_charts_df = pd.read_csv(billboard_charts)
billboard_charts_df = billboard_charts_df.drop('date', 1)
billboard_charts_df = billboard_charts_df.drop('rank', 1)
billboard_charts_df = billboard_charts_df.drop('artist', 1)
billboard_charts_df = billboard_charts_df.drop('last-week', 1)
billboard_charts_df = billboard_charts_df.drop('weeks-on-board', 1)
billboard_charts_df = billboard_charts_df.drop_duplicates()
billboard_charts_df.head()

            song  peak-rank
0     Easy On Me          1
1           Stay          1
2  Industry Baby          1
3     Fancy Like          3
4     Bad Habits          2